"""empty message

Revision ID: e13f0cc98e62
Revises: 01a3dbbecc89
Create Date: 2023-06-08 14:12:30.574999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13f0cc98e62'
down_revision = '01a3dbbecc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'rating')
    # ### end Alembic commands ###
